language:
  - java
sudo: false
dist: precise
jdk:
  - oraclejdk8

# 打包编译脚本
script:
  - mvn clean package -DskipTests

# 编译成功后触发
after_success:
  - mvn clean test
  - mvn jacoco:report
  - mvn coveralls:report

